#!/usr/bin/env bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Launch a browser with Redis Commander
## Usage: redis-commander
## Example: "ddev redis-commander"

# Determine whether to use HTTP or HTTPS based on environment
PROTOCOL="HTTP"
if [ "${DDEV_PRIMARY_URL%://*}" != "http" ] && [ -z "${GITPOD_WORKSPACE_ID:-}" ] && [ "${CODESPACES:-}" != "true" ]; then
    PROTOCOL="HTTPS"
fi

# Fetch the appropriate port within the redis-commander container
DDEV_REDIS_COMMANDER_PORT=$(ddev exec -s redis-commander sh -c "printenv | grep -w ${PROTOCOL}_EXPOSE | cut -d '=' -f 2 | cut -d ':' -f 1")

if [ -z "$DDEV_REDIS_COMMANDER_PORT" ]; then
    echo "Error: Could not retrieve Redis Commander port."
    exit 1
fi

ddev launch :"$DDEV_REDIS_COMMANDER_PORT"
